title: WAVE
#logo: .png
#description: text below image
show_downloads: false
#theme: jekyll-theme-minimal
remote_theme: mmistakes/jekyll-theme-basically-basic
#remote_theme: chrisbobbe/jekyll-theme-prologue
color-scheme: dark

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vaibhavvikas
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas
#navigation:
#  - name: Readme
#    link: ./index.html
# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _recipes
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      read_time: true
